[mgr]
prepend_keymap = [
    { on = "Q", run = "quit", desc = "Exit yazi" },
    { on = "q", run = "quit --no-cwd-file", desc = "Exit yazi without saving cwd file (no jump)" },
append_keymap = [
    { on = [
        "c",
        "r",
    ], run = "plugin relative-path", desc = "Copy relative path from the started path" },
]
