# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    { on = "Q", run = "quit", desc = "Exit yazi" },
    { on = "q", run = "quit --no-cwd-file", desc = "Exit yazi without saving cwd file (no jump)" },
    { on = [
        "s",
        "s",
    ], run = 'search --via=fd', desc = "Search files by name via fd" },
    { on = [
        "s",
        "i",
    ], run = 'search --via=fd --args="--no-ignore-vcs"', desc = "Search files by name via fd not using ignore files" },
    { on = [
        "S",
        "s",
    ], run = 'search --via=rg', desc = "Search files by content via ripgrep" },
    { on = [
        "S",
        "i",
    ], run = 'search --via=rg --args="--no-ignore"', desc = "Search files by content via ripgrep not using ignore files" },
    { on = [
        "S",
        "a",
    ], run = 'search --via=rga --args="--no-ignore"', desc = "Search files by content via ripgrep-all not using ignore files" },
]
append_keymap = [
    { on = [
        "c",
        "r",
    ], run = "plugin relative-path", desc = "Copy relative path from the started path" },
]
