[opener]
inkscape = [{ run = "inkscape %s", orphan = true, desc = "Inkscape" }]
less = [{ run = "less %s", block = true, desc = "less" }]

[open]
prepend_rules = [
    { mime = "image/svg+xml", use = [
        "open",
        "inkscape",
        "edit",
        "reveal",
    ] },
    { mime = "text/html", use = [
        "open",
        "edit",
        "reveal",
    ] },
    { mime = "text/plain", use = [
        "edit",
        "reveal",
        "less",
    ] },
]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
